services:
  - type: web
    name: mosaic-api
    env: node
    buildCommand: HUSKY=0 corepack enable pnpm && pnpm install --frozen-lockfile && pnpm run build --filter=api
    startCommand: cd apps/api && pnpm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001

  - type: web
    name: mosaic-web
    env: node
    buildCommand: HUSKY=0 corepack enable pnpm && pnpm install --frozen-lockfile && pnpm run build --filter=web
    startCommand: cd apps/web && pnpm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_URL
        fromService:
          type: web
          name: mosaic-api
          envVarKey: RENDER_INTERNAL_URL
